name: http_serve
description: A web server built using the shelf package.
# version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  async: ^2.4.0
  args: ^1.5.0
  shelf: ^0.7.5
#  shelf_rest: ^0.3.5
  grpc: ^2.1.3
  mysql1: ^0.17.0+1
  protobuf: ^0.13.12
  logging: 0.11.3+2
  mailer: ^3.0.4

dev_dependencies:
  pedantic: ^1.8.0
  test: ^1.6.4
 
